### ISSUE TITLE
Managing large stores

### ISSUE THREAD

**Issue by jreinert** [redux-zero/redux-zero#121]
Hey, I was wondering if there is a go-to solution how to manage large stores. In redux this would've been done by combining reducers. the `combineActions` function is useful but it keeps the actions at top level and doesn't allow for splitting the global application state into smaller chunks. If this is already possible, maybe adding it to the readme would be a good idea.

**Comment by matheusml** [comment]
Hi @jreinert 

What do you mean exactly with this? Can you provide some code examples on what would that be?

**Comment by jreinert** [comment]
exactly @neurosnap. I couldn't have explained it better :+1:

**Comment by matheusml** [comment]
Thanks for the explanation @neurosnap 

Answering your question @jreinert, right now we don't have a 'scoped state', but I would be open to discuss this.

**Comment by matheusml** [comment]
I'm closing this for now, but if you have more to add to this discussion, please feel free to

**Comment by ernaneluis** [comment]
still open to discussing this? I think without the scope state, things can get messed up very easily over time
