### ISSUE TITLE
Is there a way to call an action after another?

### ISSUE THREAD

**Issue by coder82** [redux-zero/redux-zero#136]
If I call an action from another action, the second one completes first.
Is there a way to have the calling action complete first?
Or set it up like, execute action x after action y in sequence?
I think redux-thunk does this but will it work with redux-zero?

Thanks.

**Comment by chanthafef** [comment]
How do you call an action from another action ? Could you provide an example ?

**Comment by chanthafef** [comment]
If you run the code below, you'll see that : 
1. both actions will execute in the correct order 
2. the store actually stays up to date all the way.

Personally, the problem I faced was that  my Example component only updated once.

```
import {h, Component} from 'preact'
import {connect} from 'redux-zero/preact'

const mapToProps = ({result}) => ({result});

const actions = () => ({
    test: (state, result) => {
        console.log('previous result', state.result)
        return {result}
    }
});

class Example extends Component {

   componentDidMount = () => {
        this.props.test(1);
        this.props.test(2);
    }
    
    render = () => {
        console.log('rendered result', this.props.result);
        return null;
    }
};

export default connect(mapToProps, actions)(Exemple)
```

I don't know about other frameworks, but to force preact components to render both times, you can call your actions like this  `setTimeout(() => actionCall())`

```
class Example extends Component {

   componentDidMount = () => {
        this.props.test(1);

        setTimeout(() => {
            this.props.test(2);
        })
    }
    
    render = () => {
        console.log('rendered result', this.props.result);
        return null;
    }
};
```

**Comment by coder82** [comment]
For example like this, essentially I call the inner action within outer action. What I want is to schedule the execution of actionInner right after actionOuter. Like it is now it completes first actionInner and then actionOuter.
```
const actions = (store) => ({
    actionOuter: () => {
        this.actionInner(); //does this work?
        return {outerCompleted:true};
    },
    actionInner: () => {
        return {innerCompleted: true};
    },
}
```

**Comment by chanthafef** [comment]
Maybe I just don't get it ... but isn't that just how pure functions work ? 

Why not just turn them aroud ?

```
const actions = (store) => ({
    actionInner: () => {
        this.actionOuter(); //does this work?
        return {innerCompleted:true};
    },
    actionOuter: () => {
        return {outerCompleted: true};
    },
}
```
Now if you call ationInner, actionOuter returns first & actionInner returns right after.

Or maybe below, it it's simpler to reason about.

```
const actions = (store) => ({
    actionInner: () => {
        return {innerCompleted:true};
    },
    actionOuter: () => {
        return {outerCompleted: true};
    },
    realAction: () => {
        this.actionOuter();
        this.actionsInner();
        return {}
    }
}
```

**Comment by matheusml** [comment]
This is not going to work because in Redux Zero, we only update the state for the last return line.

The only other way to update the state, without using `return` is to use `store.setState`.

**Comment by heatherKoo07** [comment]
Is this still not working in redux-zero? react-redux supports this with dispatch()
for example, (borrowing the above one)
```
const actions = (store) => ({
    actionOuter: () => {
        dispatch(actionInner());
        return {outerCompleted:true};
    },
    actionInner: () => {
        return {innerCompleted: true};
    },
```
