### ISSUE TITLE
redux devtools dispatch not working

### ISSUE THREAD

**Issue by coder82** [redux-zero/redux-zero#141]
I looks like if I try to dispatch an action from devtools it doesn't work...
Can you confirm that?

**Comment by matheusml** [comment]
@Kiho could you please answer this one?

**Comment by Kiho** [comment]
I am not sure understand question correctly, only a few actions were implemented here. https://github.com/redux-zero/redux-zero/blob/master/src/devtools/devtoolsMiddleware.spec.ts#L31
