### ISSUE TITLE
Adding redux-devtools options parameters

### ISSUE THREAD

**Issue by markdhel** [redux-zero/redux-zero#144]
I was wondering if it's a good idea to add [redux-devtools options](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md) parameter here? 

https://github.com/redux-zero/redux-zero/blob/07639a4dfdd8aa9d6ff8f737d1086fb931cd7992/src/devtools/devtoolsMiddleware.ts#L134

I have a situation that I needed to load 2 stores in a page and somehow it would be better if I can rename the 2 stores appropriately.

**Comment by matheusml** [comment]
Indeed. But I think you should add this after this one is accepted: #143
