### ISSUE TITLE
Release seems to be missing types/Actions.ts

### ISSUE THREAD

**Issue by teemuandersen** [redux-zero/redux-zero#151]
Version 5.0.3 introduced types for Actions (`src/types/Actions.ts`). These are however missing from the builds (5.0.3, 5.0.4). This breaks type checking:
```
node_modules/redux-zero/utils/bindActions.d.ts:2:24 - error TS2307: Cannot find module '../types/Actions'.
```

**Comment by matheusml** [comment]
@teemuandersen could you please [run this locally](https://github.com/redux-zero/redux-zero/pull/154) and check if this solved your issue?

**Comment by teemuandersen** [comment]
@matheusml Sorry that it took some time to respond. I was on holidays without laptop. But IMO that rollup line was part of it. But should the `package.json` _files_ section contain _types_ folder as well? I ran `yarn pack` and types folder was still missing.

**Comment by evenfrost** [comment]
Same for me here, types folder is missing from the package installed in node_modules. Just adding types in package.json's files should be fine to fix it.

**Comment by makinde** [comment]
Any update here? Just came across this.

**Comment by matheusml** [comment]
Version 5.1.1 will have the fix. Sorry about that.
