### ISSUE TITLE
Use via script tags?

### ISSUE THREAD

**Issue by eselquinoa** [redux-zero/redux-zero#155]
I have some code that uses preact and redux via script tags. I'm trying to use redux-zero instead of redux, but I don't see any guidance on how to use the code this way. The provided examples with import etc. all throw errors.

This link explains how it works with preact:

 https://github.com/preactjs/preact/issues/484

**Comment by matheusml** [comment]
There is a section for this right here: https://github.com/redux-zero/redux-zero#how
_Just search for UMD_

Please let me know if you're still unable to do it.
