### ISSUE TITLE
Not able to use redux-zero through UMD

### ISSUE THREAD

**Issue by jackyFeng** [redux-zero/redux-zero#165]
Hi,

We are trying to use redux-zero + Preact through UMD. According to the documentation, we put below scripts into our index.html. However, the createStore function is not available as both of script below are trying to create attribute "redux-zero" to window. I'm thinking we probably miss out something here. Could anyone help provide the example of using redux-zero through UMD?

Thanks

<script src="https://unpkg.com/redux-zero/dist/redux-zero.min.js"></script>

<script src="https://unpkg.com/redux-zero/preact/index.min.js"></script>

**Comment by matheusml** [comment]
Which version are you using?
