### ISSUE TITLE
How to ensure the sequence of the async actions?

### ISSUE THREAD

**Issue by jackyFeng** [redux-zero/redux-zero#178]
Hi,

Currently, we are implementing a filter feature with Redux-zero. We are having difficulties to ensure the state is updated according to the sequence of the actions. 
The issue we are having right now is that, because the action is async, if user fired the action multiple times before getting responses back, the state could be updated in any order depending on the time taken for the request.
We are wondering is there any best practice of solving this issue? We are thinking of writing an own middleware, but we 'd like to know if there's already an elegant solution on it.

Thanks
Jacky

**Comment by matheusml** [comment]
Hey @jackyFeng, I don't think this is something in Redux Zero's level to solve. That should probably be a middleware written on your side indeed.

If you have a hard time fixing it on our end, please let us know!

**Comment by jackyFeng** [comment]
> Hey @jackyFeng, I don't think this is something in Redux Zero's level to solve. That should probably be a middleware written on your side indeed.
> 
> If you have a hard time fixing it on our end, please let us know!

Hi @matheusml,

We indeed having some difficulties writing this middleware, any suggestions?

Thanks
